### ISSUE TITLE
support --generate-cds-archive for Java 22 or higher?

### ISSUE THREAD

**Issue by chirontt** [eclipse-justj/justj#34]
According to the comments here in `build-jre.sh` script, Java 22 or higher would support the `--generate-cds-archive` option of `jlink`:
https://github.com/eclipse-justj/justj/blob/a6e5c31b6a4bf73bff6023dd2ed068f901b70abf/releng/org.eclipse.justj.releng/build-jre.sh#L274-L275
But then in line 289:
https://github.com/eclipse-justj/justj/blob/a6e5c31b6a4bf73bff6023dd2ed068f901b70abf/releng/org.eclipse.justj.releng/build-jre.sh#L289
as well as line 298:
https://github.com/eclipse-justj/justj/blob/a6e5c31b6a4bf73bff6023dd2ed068f901b70abf/releng/org.eclipse.justj.releng/build-jre.sh#L298
the pattern to compare `$java_version` seems wrong, i.e. the compare pattern should be valid for Java 22+:
```shell
if [[ $java_version =~ ^[2-9][2-9]+(.[0-9]+(.[0-9]+)?)?$ ]]; then
```
Also, for JDKs which are not from Temurin, e.g. [IBM Semeru JDKs](https://developer.ibm.com/languages/java/semeru-runtimes/downloads/), the current code to handle them:
https://github.com/eclipse-justj/justj/blob/a6e5c31b6a4bf73bff6023dd2ed068f901b70abf/releng/org.eclipse.justj.releng/build-jre.sh#L293-L301
doesn't handle OpenJ9 JVM like that of the Temurin's, i.e. the code should be like:
```shell
else
  # Assume other JDKs are derived from OpenJDK
  vendor_url="https://jdk.java.net/"
  if grep "OpenJ9" all.properties; then
    vendor_label="OpenJDK J9"
    vendor_prefix="openjdk.j9"
  else
    vendor_label="OpenJDK Hotspot"
    vendor_prefix="openjdk.hotspot"

    if [[ $java_version =~ ^[2-9][2-9]+(.[0-9]+(.[0-9]+)?)?$ ]]; then
      generate_cds_archive="--generate-cds-archive"
    fi
  fi
fi
```
I've got a PR for the above changes ready to submit, if the above issues are considered valid and acceptable.

**Comment by merks** [comment]
Yes, I already tried to fix this missing it up the first time:

- https://github.com/eclipse-justj/justj/commit/94532b9f8029df4594dd323c2e5be6e54ec8c6b8
- https://github.com/eclipse-justj/justj/commit/17d576974a5524e2e6ae21ec99731534cd515a1e

Of course I'm happy with improvements.

Note though that the comment about Java 22 is wrong and in fact we're already doing this for Java 21:

https://github.com/eclipse-justj/justj/issues/34

Probably Java 30 is going to be a problem.  😨

**Comment by merks** [comment]
Another point to keep in mind is that we no longer will produce new Java 20 JRE because it's EOL.  So only LTS versions (11, 17, 21) and Java 23 (until EOL) and higher right now...  

There is currently a problem with Java 24 since +23:

https://github.com/adoptium/adoptium-support/issues/1198

**Comment by chirontt** [comment]
> Note though that the comment about Java 22 is wrong and in fact we're already doing this for Java 21

Yes, then the compare pattern could be, to support Java 21+:
```shell
if [[ $java_version =~ ^[2-9][1-9]+(.[0-9]+(.[0-9]+)?)?$ ]]; then
```
> Probably Java 30 is going to be a problem

Yes, Java 30 will be missed out, but it will be some 3+ years before we start worrying about it.

But I don't know how to handle the LTS versions of 11 and 17, though. Perhaps via multiple `OR` conditions to cover Java 11, 17 and 21+, like:
```shell
if [[ $java_version =~ ^[1][1,7]+(.[0-9]+(.[0-9]+)?)?$ || $java_version =~ ^[2-9][1-9]+(.[0-9]+(.[0-9]+)?)?$ ]]; then
```

**Comment by chirontt** [comment]
A complete compare pattern can be, for all Java 11, 17 and 21+ (including Java 30):
```shell
if [[ $java_version =~ ^[1][1,7]+(.[0-9]+(.[0-9]+)?)?$ || \
      $java_version =~ ^[2][1-9]+(.[0-9]+(.[0-9]+)?)?$ || \
      $java_version =~ ^[3-9][0-9]+(.[0-9]+(.[0-9]+)?)?$ ]]; then
```

**Comment by merks** [comment]
I'm not a shell expert... It would be nice just to pull out the major version number and treat it like a number that we can compare to another number...

https://unix.stackexchange.com/questions/232384/argument-string-to-integer-in-bash

**Comment by chirontt** [comment]
If you only need the Java major version number greater than 20, the regex will be simpler:
```shell
major_version_regex="^([0-9]+)"
if [[ $java_version =~ $major_version_regex ]] && (( 10#${BASH_REMATCH[1]} > 20 )); then
  generate_cds_archive="--generate-cds-archive"
fi
```

**Comment by merks** [comment]
I created this little test script:
```
for java_version in "17.0.12+7" "17" "30" "30." "30.0.1" "21" "21.1000"; do
java_major_version=${java_version%%.*}
echo $java_version " -> " $java_major_version
if (($java_major_version > 20)); then
echo "(($java_major_version > 20)) == true"
else
echo "(($java_major_version > 20)) == false"
fi
done
```

It prints these results:
```
$. version-compare.sh 
17.0.12+7  ->  17
((17 > 20)) == false
17  ->  17
((17 > 20)) == false
30  ->  30
((30 > 20)) == true
30.  ->  30
((30 > 20)) == true
30.0.1  ->  30
((30 > 20)) == true
21  ->  21
((21 > 20)) == true
21.1000  ->  21
((21 > 20)) == true
```
This seems simple and readable.  I will change the actual script this weekend when I have time.

**Comment by merks** [comment]
@chirontt 

I simplified the logic; I haven't tested yet.

For other cases, I wonder if we might initialize variables like this in some places, e.g.,
```
generate_cds_archive=${GENERATE_CDS_ARCHIVE:-"--generate-cds-archive"}
```
This way an environment variable can be set outside the script to determine the desired value, otherwise it's computed as the default value currently.

In any case, I'm not sure at this point what exactly you want to change further...

**Comment by chirontt** [comment]
> For other cases, I wonder if we might initialize variables like this in some places, e.g.,
> `generate_cds_archive=${GENERATE_CDS_ARCHIVE:-"--generate-cds-archive"}`

Yes, it does no harm, and it may help in overriding the default value when/if needed.

> I'm not sure at this point what exactly you want to change further

I've provided some comment in your above commit bec1c33, regarding other vendors' JDKs (other than Temurin's), about the possible OpenJ9 JVM in them.

**Comment by merks** [comment]
FYI, I tested on Windows x64 the following:
```
build-jre.sh  https://github.com/ibmruntimes/semeru21-binaries/releases/download/jdk-21.0.5%2B11_openj9-0.48.0/ibm-semeru-open-jdk_x64_windows_21.0.5_11_openj9-0.48.0.zip 
build-jre.sh https://corretto.aws/downloads/latest/amazon-corretto-23-x64-windows-jdk.zip 
build-jre.sh  https://github.com/adoptium/temurin24-binaries/releases/download/jdk-24+23-ea-beta/OpenJDK-jdk_x64_windows_hotspot_24_23-ea.zip
build-jre.sh https://download.java.net/openjdk/jdk23/ri/openjdk-23+37_windows-x64_bin.zip 
```
I'm not so happy with overlapping vendor prefixes which was only done historically to make it easy to switch from openjdk URLs to adoptium URL without changing the bundle symbolic names.   But environment variables can be used to override the default.

**Comment by chirontt** [comment]
Using the latest from master, I've tested similar JDKs on my Linux x64 box:
```shell
export JDK_URLS_LINUX="https://github.com/ibmruntimes/semeru21-binaries/releases/download/jdk-21.0.5%2B11_openj9-0.48.0/ibm-semeru-open-jdk_x64_linux_21.0.5_11_openj9-0.48.0.tar.gz \
https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz \
https://github.com/adoptium/temurin24-binaries/releases/download/jdk-24%2B23-ea-beta/OpenJDK-jdk_x64_linux_hotspot_24_23-ea.tar.gz \
https://download.oracle.com/java/23/latest/jdk-23_linux-x64_bin.tar.gz"
./build-jre.sh
```
and I've encountered some errors:
- for the Amazon Corretto JDK:  https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz, it's uncompressed into a directory **not** starting with `jdk`, causing the script to fail later:
```
./build-jre.sh: line 202: jdk[1-9-]*/bin/java: No such file or directory
```
I'm not sure what we can do about this JDK, apart from considering it an "edge case" to be ignored for now.
- for the Oracle-provided JDK: https://download.oracle.com/java/23/latest/jdk-23_linux-x64_bin.tar.gz, note its file name starting with `jdk` which causes the script to delete it after downloading, due to this line:
https://github.com/eclipse-justj/justj/blob/14a4c04c98c89dc149f176c38f66b36e877c3de1/releng/org.eclipse.justj.releng/build-jre.sh#L185
Not sure what to do about this JDK either. Maybe the above line 185 should be moved to the start of the loop, i.e. to line 160? But even after the move, subsequent line 186 to detect the uncompressed JDK directory:
https://github.com/eclipse-justj/justj/blob/14a4c04c98c89dc149f176c38f66b36e877c3de1/releng/org.eclipse.justj.releng/build-jre.sh#L186
would cause the wrong expansion by the shell:
```
+ jdk='jdk-23.0.1 jdk-23_linux-x64_bin.tar.gz'
```
So I consider this Oracle-provided JDK as another "edge case" to be ignore for now.

Anyway, thanks @merks for all your help.

Last question: is there some task/goal in the existing Maven build script to generate the JREs *and* then create the p2 repo for them at the same time?

**Comment by merks** [comment]
It seems odd that they would name the folder in the windows zip different from the one in the tar.gz:

![image](https://github.com/user-attachments/assets/f57a4971-a53b-4943-b893-6016304aa0d0)

![image](https://github.com/user-attachments/assets/c1cdfe94-a6c5-4b3f-9e75-4b13317995ce)

This job does everything:

https://ci.eclipse.org/justj/job/build-jres/

it uses this:

**Comment by merks** [comment]
For macos it has yet another name:

![image](https://github.com/user-attachments/assets/e6339c15-eb14-43ec-8b5c-29e3d856df68)

It all seems a bit "random".   😢

**Comment by merks** [comment]
Something like this could get the root name from the tar file:
```
tar ztf /d/stuff/amazon-corretto-23.0.1.8.1-macosx-x64.tar.gz | head -1
```
Or this the root of the zip:
```
unzip -qql amazon-corretto-21-x64-windows-jdk.zip | head -n1 | tr -s ' ' | cut -d' ' -f5-
```
And then hope all the OSes produce the expected results from such a script...

**Comment by merks** [comment]
The issue with the folder name in the archive should be working now too, at least as far as I've tested in on Windows and in the build

https://ci.eclipse.org/justj/job/build-jres/

(The build is failing because of signing problems on Windows and MacOs for Java 24+26.)

**Comment by chirontt** [comment]
I've re-run my script for Linux and it works now for the Amazon JDK (thanks for your hard work!), but still fails for the Oracle-provided JDK: https://download.oracle.com/java/23/latest/jdk-23_linux-x64_bin.tar.gz, as it works out the uncompressed JDK folder name wrongly:
```
+ jdk=jdk-23.0.1LICENSE
```
where the correct folder name should have been:
```
+ jdk=jdk-23.0.1
```
I think it's due to this line:
https://github.com/eclipse-justj/justj/blob/dc8c90cc4ea425645fa47b460d3e10236f9d4a75/releng/org.eclipse.justj.releng/build-jre.sh#L189
Something's screwy there, but as I said before, it's an "edge case" to be ignored for now.

**Comment by merks** [comment]
It looks like that tar file doesn't include folder names but only file names.  Stripping out `/.*` rather than just the `/` should cover that case:
``
$echo $(tar -ztf jdk-23_linux-x64_bin.tar.gz | head -1 | sed 's%/.*%%')
jdk-23.0.1
```
